

###
## Local Testing
## Create a Post
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "title": "Hello!",
  "content": "This is a sample notes"
}

### List all posts.

GET http://localhost:8080/api/notes
Accept: application/json

###

## This is a testing against the cloud environment
POST http://sprin-sprin-q1oj581ljahz-1433862113.us-east-1.elb.amazonaws.com/api/notes
Content-Type: application/json

{
  "title": "Hello!",
  "content": "This is a sample notes"
}

###

GET http://sprin-sprin-q1oj581ljahz-1433862113.us-east-1.elb.amazonaws.com/api/notes
Accept: application/json

###

##